### ISSUE TITLE
Feature: Compatibility with extensions that override tab size

### ISSUE THREAD

**Issue by glebm** [glebm/render-whitespace-on-github#2] opened 2017-10-03 11:15 UTC
Need to use `getComputedStyle`, as not all of these extensions update `data-tab-size`.
Also need to decrease extension priority so that it runs after these other extensions.

**Comment by FichteFoll** [comment] 2017-11-18 18:30
I'm using [Refined Github](https://github.com/sindresorhus/refined-github/) with this, where this issue surfaces. Would love to see this fixed.

**Comment by glebm** [comment] 2017-11-27 15:06
It'd be nice if *Refined Github* also updated `data-tab-size`, since it's such a popular extension.

**Comment by FichteFoll** [comment] 2017-11-27 16:47
Redirected to https://github.com/sindresorhus/refined-github/issues/828. No idea about the details, but hopefully this will be enough.

Maybe you could tune in with a few details?

**Comment by FichteFoll** [comment] 2017-11-29 00:32
So, uhm, is this supposed to be fixed with 1.3.7 and Refined Github now? Because it does't seem that way to me.

![img](https://camo.githubusercontent.com/3f9ab56dc02eec03b4456dd052157fdcb3fcee8e/68747470733a2f2f78302e61742f41344a2e706e67)

https://github.com/wbond/package_control_channel/pull/6734/files

**Comment by glebm** [comment] 2017-11-29 00:45
I'll have a look tomorrow but for now can you confirm all the GitHub extensions you have and their versions?

**Comment by FichteFoll** [comment] 2017-11-29 00:54
Render Whiitespace on Github 1.3.7
Refined Github 17.11.26.1432
Notifications Preview for Github 1.0.4

**Comment by glebm** [comment] 2017-11-29 11:11
I can't reproduce the issue, here is what I see:

![rws-no-repro](https://user-images.githubusercontent.com/216339/33372443-fb78a758-d4f5-11e7-833d-cba28b87fd3e.PNG)

Here is how you can figure out what's happening.

1. Put a breakpoint here and reload the page:

   ![rws-breakpoint](https://user-images.githubusercontent.com/216339/33372319-84decaa0-d4f5-11e7-9dd5-c949b3ecb60c.PNG)

2. Check that `window.getComputedStyle(root)['tab-size']` returns "4". If it doesn't, head over to the Elements panel and figure out where the different value comes from.

The GitHub tab size for that file is "8" but Refined GitHub sets the tab size to "4".

**Comment by FichteFoll** [comment] 2017-11-29 17:07
I just realized I haven't noted that I'm using FireFox (57, that is).

`window.getComputedStyle(root)['tab-size']` is undefined and `window.getComputedStyle(root)` does not have any entry beginning with `tab`.

**Comment by glebm** [comment] 2017-11-29 17:17
Looks like a 6-year old bug: https://bugzilla.mozilla.org/show_bug.cgi?id=737785

How about this?

```javascript
window.getComputedStyle(root)['-moz-tab-size']
```

**Closed as completed** 2017-11-29 18:04 UTC
Labels: enhancement

**Comment by glebm** [comment] 2017-11-29 18:08
Fixed and pushed a new version everywhere except Chrome webstore (Chrome is not affected by this bug).

**Comment by FichteFoll** [comment] 2017-11-29 22:13
Thanks, confirmed working.

I presume https://github.com/sindresorhus/refined-github/issues/828 is no longer needed with this?

**Comment by glebm** [comment] 2017-11-29 22:36
That's right :+1:
